const citiesArr = [
    "A Coruña",
    "Alacuás",
    "Albacete",
    "Albal",
    "Alboraya",
    "Alcalá de Henares",
    "Alcantarilla",
    "Alcobendas",
    "Alcorcón",
    "Aldaya",
    "Alfafar",
    "Algeciras",
    "Alicante",
    "Almería",
    "Archena",
    "Armilla",
    "Arona",
    "Arrecife",
    "Arroyomolinos",
    "Arucas",
    "Avilés",
    "Azuqueca de Henares",
    "Badajoz",
    "Badalona",
    "Barañáin",
    "Barcelona",
    "Bañolas",
    "Benalmádena",
    "Benicàssim",
    "Benidorm",
    "Bilbao",
    "Blanes",
    "Boadilla del Monte",
    "Bormujos",
    "Burgos",
    "Burjasot",
    "Calafell",
    "Calella",
    "Calpe",
    "Camas",
    "Cambrils",
    "Canovellas",
    "Cardedeu",
    "Cartagena",
    "Castelldefels",
    "Castellón de la Plana",
    "Castilleja de la Cuesta",
    "Catarroja",
    "Ciudad de Ceuta",
    "Ciudad de Melilla",
    "Collado-Villalba",
    "Cádiz",
    "Córdoba",
    "Donostia",
    "Dos Hermanas",
    "Durango",
    "El Astillero",
    "El Prat de Llobregat",
    "Elche",
    "Elda",
    "Erandio",
    "Esplugas de Llobregat",
    "Figueras",
    "Fuengirola",
    "Fuenlabrada",
    "Gandía",
    "Gavá",
    "Getafe",
    "Gijón",
    "Girona",
    "Granada",
    "Granollers",
    "Guadalajara",
    "Guernica y Luno",
    "Huelva",
    "Humanes de Madrid",
    "Ibiza",
    "Igualada",
    "Irún",
    "Jaén",
    "Jerez de la Frontera",
    "La Corredoría",
    "La Laguna",
    "La Línea de la Concepción",
    "Las Palmas",
    "Las Rozas de Madrid",
    "Leganés",
    "León",
    "Lleida",
    "Logroño",
    "Madrid",
    "Mairena del Aljarafe",
    "Majadahonda",
    "Malgrat de Mar",
    "Manises",
    "Manlleu",
    "Manresa",
    "Maracena",
    "Marbella",
    "Martorell",
    "Mataró",
    "Mejorada del Campo",
    "Mislata",
    "Mollet",
    "Molíns de Rey",
    "Moncada",
    "Murcia",
    "Málaga",
    "Mérida",
    "Móstoles",
    "Olesa de Montserrat",
    "Olot",
    "Ourense",
    "Oviedo",
    "Paiporta",
    "Palafrugell",
    "Palamós",
    "Palma",
    "Pamplona",
    "Parla",
    "Paterna",
    "Petrel",
    "Portugalete",
    "Premiá de Mar",
    "Puzol",
    "Reus",
    "Rincón de la Victoria",
    "Ripollet",
    "Roquetas de Mar",
    "Rubí",
    "Sabadell",
    "Salamanca",
    "Salou",
    "Salt",
    "San Adrián de Besós",
    "San Andrés de la Barca",
    "San Baudilio de Llobregat",
    "San Cugat del Vallés",
    "San Felíu de Guixols",
    "San Felíu de Llobregat",
    "San Fernando de Henares",
    "San Fernando",
    "San Juan de Alicante",
    "San Juan de Aznalfarache",
    "San Juan de Vilasar",
    "San Juan Despí",
    "San Pedro del Pinatar",
    "San Sebastián de los Reyes",
    "San Vicente de Baracaldo",
    "San Vicente del Raspeig",
    "San Vicente dels Horts",
    "Sant Just Desvern",
    "Santa Cruz",
    "Santa Perpetua de Moguda",
    "Santander",
    "Santiago de Compostela",
    "Santurce-Antiguo",
    "Sestao",
    "Sevilla",
    "Tarragona",
    "Tarrasa",
    "Telde",
    "Toledo",
    "Tomares",
    "Torredembarra",
    "Torrejón de Ardoz",
    "Torrelavega",
    "Torrelodones",
    "Torremolinos",
    "Torrente",
    "Torrevieja",
    "Utebo",
    "Valdemoro",
    "Valencia",
    "Valladolid",
    "Vendrell",
    "Vich",
    "Vigo",
    "Viladecáns",
    "Vilaseca de Solcina",
    "Villafranca del Panadés",
    "Villajoyosa",
    "Villanueva y Geltrú",
    "Vitoria-Gasteiz",
    "Zaragoza",
    "Zarautz"
  ];
  
  export default citiesArr
  